CREATE DATABASE IF NOT EXISTS MGF;

USE MGF;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    login VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE
);

ALTER TABLE users ADD COLUMN status ENUM('admin', 'user') DEFAULT 'user';

GRANT ALL PRIVILEGES ON MGF.* TO 'nfinohenov'@'localhost';

FLUSH PRIVILEGES;


