CREATE DATABASE IF NOT EXISTS MGF;

USE MGF;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    avatar VARCHAR(10) NOT NULL
);
CREATE USER IF NOT EXISTS 'rootuser'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON mgf.* TO 'rootuser'@'localhost';
FLUSH PRIVILEGES;